WebKitSettings.cpp: fix missing include
/home/thomas/br-test-pkg/bootlin-x86-64-musl/build/webkitgtk-2.46.1/Source/WebKit/UIProcess/API/glib/WebKitSettings.cpp:4276:5: error: ‘GUniquePtr’ was not declared in this scope
 4276 |     GUniquePtr<GParamSpec*> properties(g_object_class_list_properties(klass, &totalProperties));
      |     ^~~~~~~~~~

Signed-off-by: Thomas Devoogdt <thomas@devoogdt.com>